# gpux.yml - Sentiment Analysis Example
name: sentiment-analysis
version: 1.0.0
description: "BERT-based sentiment analysis model for text classification"

model:
  source: ./sentiment_model.onnx
  format: onnx

inputs:
  input_ids:
    type: int64
    shape: [1, 512]
    required: true
    description: "Tokenized input text"
  attention_mask:
    type: int64
    shape: [1, 512]
    required: true
    description: "Attention mask for input tokens"

outputs:
  logits:
    type: float32
    shape: [1, 2]
    labels: [negative, positive]
    description: "Raw logits for sentiment classification"

runtime:
  gpu:
    memory: 2GB
    backend: auto

serving:
  port: 8080
  host: 0.0.0.0
  batch_size: 1
  timeout: 5

preprocessing:
  tokenizer: bert-base-uncased
  max_length: 512
